volumes:
  media_volume:
    name: best_media

  redis_volume:
    name: best_cache

  postgres_volume:
    name: best_db

networks:
  backend:
    driver: bridge
    name: best_backend

services:
  telegram_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - bot/.env
      - redis/.env
      - postgres/.env
    networks:
      - backend
    volumes:
      - media_volume:/usr/src/app/resources
      - ./bot:/app
    depends_on:
      - postgres

  redis:
    image: redis:8.2.2
    restart: unless-stopped
    env_file: redis/.env
    ports:
      - "6379:6379"  # Проброс порта Redis на хост
    networks:
      - backend
    volumes:
      - redis_volume:/data

  postgres:
    image: postgres:17.6
    restart: unless-stopped
    env_file: postgres/.env
    ports:
      - "5433:5432"  # Проброс порта: хост:контейнер (5433 на хосте -> 5432 в контейнере)
    networks:
      - backend
    volumes:
      - postgres_volume:/var/lib/postgresql/data
