services:
  telegram_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - media_volume:/usr/src/app/resources
      - ./bot/logs:/usr/src/app/logs
    #      - ./bot/database/migrations/versions:/usr/src/app/database/migrations/versions
    env_file:
      - bot/.env
      - redis/.env
  
  #  postgres:
  #    image: postgres:17.4
  #    restart: unless-stopped
  #    env_file: postgres/.env
  #    expose:
  #      - 5432
  #    volumes:
  #      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    restart: unless-stopped
    env_file: redis/.env
    expose:
      - 6379
    volumes:
      - redis_volume:/data

volumes:
  media_volume:
    driver: local
  
  #  postgres_volume:
  #    driver: local

  redis_volume:
    driver: local
