"""initial schema

Revision ID: 5b34f205bf3e
Revises: 
Create Date: 2026-06-29 15:13:50.730484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b34f205bf3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='название группы товаров'),
    sa.PrimaryKeyConstraint('id'),
    comment='Название категории'
    )
    op.create_table('lbg_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_key', sa.String(length=255), nullable=False, comment='Ключ сопоставления: best-email или нормализованное ФИО'),
    sa.Column('full_name_ru', sa.String(length=255), nullable=True, comment='ФИО на русском'),
    sa.Column('full_name_en', sa.String(length=255), nullable=True, comment='ФИО на английском'),
    sa.Column('gender', sa.String(length=16), nullable=True, comment='male/female'),
    sa.Column('best_email', sa.String(length=255), nullable=True, comment='Почта @best-eu.org'),
    sa.Column('personal_email', sa.String(length=255), nullable=True, comment='Личная почта'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='Нормализованный телефон'),
    sa.Column('vk_url', sa.String(length=255), nullable=True, comment='ВКонтакте'),
    sa.Column('telegram', sa.String(length=255), nullable=True, comment='Telegram'),
    sa.Column('facebook', sa.String(length=255), nullable=True, comment='Facebook'),
    sa.Column('instagram', sa.String(length=255), nullable=True, comment='Instagram'),
    sa.Column('faculty', sa.String(length=255), nullable=True, comment='Институт/факультет'),
    sa.Column('study_group', sa.String(length=64), nullable=True, comment='Учебная группа'),
    sa.Column('home_address', sa.Text(), nullable=True, comment='Домашний адрес / общежитие'),
    sa.Column('dormitory', sa.String(length=255), nullable=True, comment='Общежитие (если выделено)'),
    sa.Column('angel_name', sa.String(length=255), nullable=True, comment='Ангел/ментор'),
    sa.Column('status_field', sa.Text(), nullable=True, comment='Должность/роли (Status/field)'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='Дата рождения'),
    sa.Column('active_since', sa.Date(), nullable=True, comment='Начало активности'),
    sa.Column('active_till', sa.Date(), nullable=True, comment='Окончание активности'),
    sa.Column('local_involvement', sa.Text(), nullable=True),
    sa.Column('international_involvement', sa.Text(), nullable=True),
    sa.Column('best_events', sa.Text(), nullable=True),
    sa.Column('workplace', sa.Text(), nullable=True),
    sa.Column('membership_category', sa.String(length=64), nullable=True, comment='board/full_member/baby_member/observer/alumni/ex_*/inactive'),
    sa.Column('membership_status', sa.String(length=32), nullable=True, comment='Грубый статус: active/alumni/ex/inactive'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активный член'),
    sa.Column('source_sheet', sa.String(length=255), nullable=True, comment='Имя листа-источника'),
    sa.Column('source_section', sa.String(length=255), nullable=True, comment='Секция листа'),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Полный сырой слепок строк'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Первое появление в таблице'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Последнее появление в таблице'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Последний прогон синхронизации'),
    sa.Column('removed_from_sheet_at', sa.DateTime(timezone=True), nullable=True, comment='Когда пропал из таблицы'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Участник LBG (синхронизация из Google Sheets)'
    )
    op.create_index(op.f('ix_lbg_members_best_email'), 'lbg_members', ['best_email'], unique=False)
    op.create_index(op.f('ix_lbg_members_identity_key'), 'lbg_members', ['identity_key'], unique=True)
    op.create_index(op.f('ix_lbg_members_membership_category'), 'lbg_members', ['membership_category'], unique=False)
    op.create_index(op.f('ix_lbg_members_membership_status'), 'lbg_members', ['membership_status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID платежа'),
    sa.Column('cost', sa.Integer(), nullable=False, comment='Стоимость'),
    sa.Column('is_paid', sa.Boolean(), nullable=False, comment='Статус оплаты'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='Дата создания записи о платеже'),
    sa.Column('bill', sa.String(length=255), nullable=True, comment='Ссылка на чек'),
    sa.Column('payed_date', sa.DateTime(), nullable=True, comment='Дата фактической оплаты'),
    sa.PrimaryKeyConstraint('id'),
    comment='Платеж'
    )
    op.create_table('requisites',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор реквизитов'),
    sa.Column('details', sa.String(length=255), nullable=False, comment='Подробная информация о реквизитах'),
    sa.PrimaryKeyConstraint('id'),
    comment='Платежные реквизиты'
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='ID в Telegram'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Имя пользователя'),
    sa.Column('telegram_username', sa.String(length=32), nullable=True, comment='Telegram @username (для авто-связи с LbgMember)'),
    sa.Column('lbg_member_id', sa.Integer(), nullable=True, comment='Связанный участник LBG (если опознан)'),
    sa.ForeignKeyConstraint(['lbg_member_id'], ['lbg_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Человек'
    )
    op.create_index(op.f('ix_persons_lbg_member_id'), 'persons', ['lbg_member_id'], unique=True)
    op.create_index(op.f('ix_persons_telegram_id'), 'persons', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_persons_telegram_username'), 'persons', ['telegram_username'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False, comment='Адрес места хранения'),
    sa.Column('person_id', sa.Integer(), nullable=False, comment='у кого хранится'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Место хранения'
    )
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID возврата'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название товара'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='ID инициировавшего возврат'),
    sa.Column('payment_id', sa.Integer(), nullable=False, comment='ID платежа, по которому осуществляется возврат'),
    sa.ForeignKeyConstraint(['customer_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Товарная единица'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='название товара'),
    sa.Column('count', sa.Integer(), nullable=False, comment='количество товара'),
    sa.Column('unit', sa.String(length=255), nullable=False, comment='единица измерения'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='к какой категории относится'),
    sa.Column('place_id', sa.Integer(), nullable=False, comment='где хранится'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Товарная единица'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('refunds')
    op.drop_table('places')
    op.drop_index(op.f('ix_persons_telegram_username'), table_name='persons')
    op.drop_index(op.f('ix_persons_telegram_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_lbg_member_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_table('requisites')
    op.drop_table('payments')
    op.drop_index(op.f('ix_lbg_members_membership_status'), table_name='lbg_members')
    op.drop_index(op.f('ix_lbg_members_membership_category'), table_name='lbg_members')
    op.drop_index(op.f('ix_lbg_members_identity_key'), table_name='lbg_members')
    op.drop_index(op.f('ix_lbg_members_best_email'), table_name='lbg_members')
    op.drop_table('lbg_members')
    op.drop_table('categories')
    # ### end Alembic commands ###
