"""add vpn subscriptions table

Revision ID: a1c00b47f3ed
Revises: 5b34f205bf3e
Create Date: 2026-08-04 19:43:54.427863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c00b47f3ed'
down_revision: Union[str, None] = '5b34f205bf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID подписки'),
    sa.Column('person_id', sa.Integer(), nullable=False, comment='Владелец подписки'),
    sa.Column('xui_email', sa.String(length=255), nullable=False, comment='Идентификатор клиента в панели (best-почта или lbg-<person_id>)'),
    sa.Column('sub_id', sa.String(length=64), nullable=False, comment='subId клиента — ключ ссылки-подписки'),
    sa.Column('xui_client_uuid', sa.String(length=64), nullable=False, comment='UUID клиента в панели (поле id)'),
    sa.Column('protocol', sa.String(length=16), server_default='xui', nullable=False, comment='Тип подписки: xui (задел под awg)'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='active/revoked'),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда подписка выдана'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Когда подписка отключена'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_id'),
    comment='VPN-подписка, выданная ботом'
    )
    op.create_index(op.f('ix_vpn_subscriptions_person_id'), 'vpn_subscriptions', ['person_id'], unique=True)
    op.create_index(op.f('ix_vpn_subscriptions_status'), 'vpn_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_vpn_subscriptions_xui_email'), 'vpn_subscriptions', ['xui_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_subscriptions_xui_email'), table_name='vpn_subscriptions')
    op.drop_index(op.f('ix_vpn_subscriptions_status'), table_name='vpn_subscriptions')
    op.drop_index(op.f('ix_vpn_subscriptions_person_id'), table_name='vpn_subscriptions')
    op.drop_table('vpn_subscriptions')
    # ### end Alembic commands ###
