[project]
name = "BEST_sicret_bot"
version = "0.1.0"
description = "Telegram bot for SPb LBG - @BEST_sicret_bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiodns>=4.0.4",
    "aiogram>=3.29.0",
    "aiogram-dialog>=2.6.0",
    "aiohttp[sppedups]>=3.14.1",
    "alembic>=1.18.4",
    "alembic-postgresql-enum>=1.10.0",
    "asyncpg>=0.31.0",
    "colorama>=0.4.6",
    "docxtpl>=0.20.2",
    "fluent-runtime>=0.4.0",
    "fluent-syntax>=0.19.0",
    "fuzzywuzzy>=0.18.0",
    "jsonschema>=4.26.0",
    "pycares>=5.0.1",
    "pydantic-settings>=2.14.1",
    "python-levenshtein>=0.27.3",
    "redis[hiredis]>=8.0.0",
    "sqlalchemy[asyncio]>=2.0.51",
    "structlog>=26.1.0",
    "ujson>=5.13.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]
